import type { UserSession, PersonaComparison } from "../types.js";
import { generateSessionReport } from "./generator.js";
import { generateComparisonReport } from "./comparison.js";

/**
 * Generate a standalone HTML report from a user session.
 */
export function generateHtmlReport(session: UserSession): string {
  const markdown = generateSessionReport(session);
  const { persona, summary } = session;

  const frictionColor = summary.frictionScore <= 3 ? "#22c55e"
    : summary.frictionScore <= 6 ? "#eab308"
    : "#ef4444";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UserFlow Report — ${persona.name} on ${session.startUrl}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; background: #f8f9fa; padding: 2rem; max-width: 900px; margin: 0 auto; }
    h1 { font-size: 1.8rem; margin-bottom: 0.5rem; color: #1a1a2e; }
    h2 { font-size: 1.3rem; margin: 2rem 0 1rem; color: #16213e; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
    h3 { font-size: 1.1rem; margin: 1.5rem 0 0.5rem; color: #0f3460; }
    .card { background: white; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .metric { display: inline-block; padding: 0.5rem 1rem; border-radius: 8px; margin: 0.25rem; font-weight: 600; }
    .friction-score { background: ${frictionColor}20; color: ${frictionColor}; font-size: 1.5rem; padding: 0.75rem 1.5rem; }
    .goal-yes { background: #22c55e20; color: #22c55e; }
    .goal-no { background: #ef444420; color: #ef4444; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; }
    blockquote { border-left: 3px solid #6366f1; padding-left: 1rem; margin: 1rem 0; color: #4a5568; font-style: italic; }
    .step { border-left: 3px solid #e2e8f0; padding-left: 1rem; margin: 1rem 0; }
    .step.has-friction { border-left-color: #ef4444; }
    .friction-tag { display: inline-block; padding: 0.2rem 0.5rem; border-radius: 4px; font-size: 0.8rem; font-weight: 600; margin-right: 0.5rem; }
    .friction-low { background: #dbeafe; color: #1d4ed8; }
    .friction-medium { background: #fef3c7; color: #92400e; }
    .friction-high { background: #fee2e2; color: #991b1b; }
    .friction-critical { background: #991b1b; color: white; }
    .emotion-bar { display: flex; gap: 0.25rem; margin: 1rem 0; flex-wrap: wrap; }
    .emotion-step { padding: 0.3rem 0.6rem; border-radius: 6px; font-size: 0.8rem; background: #f1f5f9; }
    .persona-info { color: #64748b; font-size: 0.9rem; }
    footer { margin-top: 3rem; text-align: center; color: #94a3b8; font-size: 0.85rem; }
  </style>
</head>
<body>
  <div class="card">
    <h1>UserFlow Session Report</h1>
    <p class="persona-info"><strong>${persona.name}</strong> — ${persona.description}</p>
    <p class="persona-info">Goals: ${persona.goals.join(", ")}</p>
    <p class="persona-info">URL: <a href="${session.startUrl}">${session.startUrl}</a></p>
  </div>

  <div class="card">
    <h2>Summary</h2>
    <span class="metric friction-score">Friction: ${summary.frictionScore}/10</span>
    <span class="metric ${summary.goalAchieved ? "goal-yes" : "goal-no"}">${summary.goalAchieved ? "Goal Achieved ✅" : "Goal Not Achieved ❌"}</span>
    <span class="metric" style="background: #f1f5f9;">${summary.totalSteps} steps</span>

    <h3>Emotional Journey</h3>
    <div class="emotion-bar">
      ${summary.emotionalJourney.map((e, i) => `<span class="emotion-step">Step ${i}: ${e}</span>`).join("\n      ")}
    </div>
    <p>${summary.dropOffRisk}</p>
  </div>

  ${session.steps.length > 0 ? `
  <div class="card">
    <h2>Step-by-Step Walkthrough</h2>
    ${session.steps.map((step) => `
    <div class="step ${step.frictionPoints.length > 0 ? "has-friction" : ""}">
      <h3>Step ${step.index}: ${step.page.title || step.page.url}</h3>
      <p><strong>${step.emotionalState}</strong> | ${step.action.type}${step.action.target ? ` → <code>${step.action.target}</code>` : ""}</p>
      <blockquote>${step.thought}</blockquote>
      ${step.frictionPoints.map((f) => `<p><span class="friction-tag friction-${f.severity}">${f.severity.toUpperCase()}</span> ${f.description}<br><em>→ ${f.suggestion}</em></p>`).join("\n      ")}
    </div>`).join("\n")}
  </div>` : ""}

  ${summary.recommendations.length > 0 ? `
  <div class="card">
    <h2>Recommendations</h2>
    <ol>
      ${summary.recommendations.map((r) => `<li>${r}</li>`).join("\n      ")}
    </ol>
  </div>` : ""}

  <footer>
    Generated by <strong>UserFlow MCP</strong> — Persona-based UX feedback for developers
  </footer>
</body>
</html>`;
}

/**
 * Generate an HTML comparison report for multiple personas.
 */
export function generateHtmlComparisonReport(comparison: PersonaComparison): string {
  const markdown = generateComparisonReport(comparison);

  // For comparison reports, use markdown-based output wrapped in basic HTML
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UserFlow Multi-Persona Comparison</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; background: #f8f9fa; padding: 2rem; max-width: 900px; margin: 0 auto; }
    pre { background: #f1f5f9; padding: 1rem; border-radius: 8px; overflow-x: auto; white-space: pre-wrap; }
    footer { margin-top: 3rem; text-align: center; color: #94a3b8; font-size: 0.85rem; }
  </style>
</head>
<body>
  <pre>${escapeHtml(markdown)}</pre>
  <footer>Generated by <strong>UserFlow MCP</strong></footer>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
